"""Application constants and configuration values."""

from __future__ import annotations

# UI Constants
DEFAULT_WINDOW_WIDTH = 1600
DEFAULT_WINDOW_HEIGHT = 900
DEFAULT_BUTTON_HEIGHT = 32
DEFAULT_DROPDOWN_WIDTH = 150
DEFAULT_DROPDOWN_HEIGHT = 200
DEFAULT_SCROLL_HEIGHT = 200
DEFAULT_COVER_HEIGHT = 200

# Thumbnail and Tile Constants
DEFAULT_THUMBNAIL_SIZE = (128, 128)
DEFAULT_TILE_SIZE = (1024, 1024)
DEFAULT_IMAGES_PER_TILE = 64
DEFAULT_THUMBNAIL_MAX_SIZE = 300

# Gallery and Pagination Constants
DEFAULT_PAGE_SIZE = 200
DEFAULT_BATCH_SIZE = 128
DEFAULT_ANN_CANDIDATE_LIMIT = 32

# Database Constants
FILE_PATH_MAX_LENGTH = 1024
TIME_PERIOD_MAX_LENGTH = 32
DEFAULT_AGE_PENALTY_WEIGHT = 0.15

# Performance Constants
READ_CHUNK_SIZE = 1024 * 1024  # 1MB chunks

# Test Constants
TEST_FACE_COUNT = 2
TEST_IMAGE_COUNT = 3
TEST_CLUSTER_COUNT = 2
