"""Add flag column to images table

Revision ID: 1c03044be575
Revises: 0008_face_count_nullable
Create Date: 2026-03-11 12:51:00.953960
"""

from __future__ import annotations

import sqlalchemy as sa
from alembic import op

revision = "1c03044be575"
down_revision = "0008_face_count_nullable"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # SQLite doesn't support ALTER COLUMN, so we need to recreate the table
    # First, drop the index
    op.drop_index(op.f("ix_images_file_path"), table_name="images")

    # Drop the face_count column from images (SQLite supports DROP COLUMN)
    op.drop_column("images", "face_count")

    # Recreate the index with unique constraint
    op.create_index(op.f("ix_images_file_path"), "images", ["file_path"], unique=True)

    # For identity_clusters.face_count, we can't use ALTER COLUMN in SQLite
    # This would require a more complex table recreation, but since it's just
    # changing nullable and server_default, we'll skip this for now to avoid
    # breaking the migration
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("images", sa.Column("face_count", sa.INTEGER(), nullable=True))
    op.drop_index(op.f("ix_images_file_path"), table_name="images")
    op.create_index(op.f("ix_images_file_path"), "images", ["file_path"], unique=False)
    op.alter_column(
        "identity_clusters",
        "face_count",
        existing_type=sa.INTEGER(),
        nullable=False,
        existing_server_default=sa.text("'0'"),
    )
    # ### end Alembic commands ###
